sudo: required

services:
  - docker

language: bash

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t jrromb/rasp-share .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jrromb/rasp-share
  - docker logout